### SQLite

In [1]:
import sqlite3
sqlite3.sqlite_version

'3.50.4'

#### SQLite 데이터베이스에 데이터 입력하기

In [2]:
import sqlite3
conn = sqlite3.connect('example.db')

In [3]:
print(conn)

<sqlite3.Connection object at 0x00000295EFE41B70>

In [4]:
conn = sqlite3.connect("contact.db")

In [5]:
cursor = conn.cursor()

In [6]:
try :
    cursor.execute("DROP TABLE contact")
except:
    print("삭제할 테이블이 존재하지 않습니다.")

삭제할 테이블이 존재하지 않습니다.

In [7]:
cursor.execute("""CREATE TABLE contact(
    name text, 
    age int, 
    email text)
""")

In [8]:
cursor.execute("INSERT INTO contact VALUES('kim', 30, 'kim@naver.com')")
cursor.execute("INSERT INTO contact VALUES('lee', 35, 'lee@daum.net')")
cursor.execute("INSERT INTO contact VALUES('park', 40, 'heo@coderby.com')")

In [9]:
conn.commit()
conn.close()

#### SQLite 데이터베이스에서 데이터 조회하기

In [10]:
conn = sqlite3.connect("contact.db")

In [11]:
cursor = conn.cursor()

In [12]:
cursor.execute("SELECT * FROM contact")

In [13]:
for row in cursor:
    print(row)

('kim', 30, 'kim@naver.com')
('lee', 35, 'lee@daum.net')
('park', 40, 'heo@coderby.com')

In [14]:
cursor.execute("SELECT * FROM contact")
cursor.fetchone()

('kim', 30, 'kim@naver.com')

In [15]:
contact_data = cursor.fetchall()

In [16]:
contact_data

[('lee', 35, 'lee@daum.net'), ('park', 40, 'heo@coderby.com')]

In [17]:
#qmark 스타일 파라미터 인수
cursor.execute("SELECT * FROM contact WHERE email=?", 
               ("heo@coderby.com",))
cursor.fetchall()

[('park', 40, 'heo@coderby.com')]

In [18]:
# named 스타일 파라미터 인수
user_email = "heo@coderby.com"
cursor.execute("SELECT * FROM contact WHERE email=:email", 
               {"email":user_email})
cursor.fetchall()

[('park', 40, 'heo@coderby.com')]

In [19]:
conn.close()

#### SQLite 데이터베이스에서 데이터 수정/삭제하기

In [20]:
import sqlite3
conn = sqlite3.connect("contact.db")

In [21]:
cur = conn.cursor()
cur.execute("UPDATE contact SET name='heo' WHERE email='heo@coderby.com'")

In [22]:
cur.execute("SELECT * FROM contact")
cur.fetchall()

[('kim', 30, 'kim@naver.com'),
 ('lee', 35, 'lee@daum.net'),
 ('heo', 40, 'heo@coderby.com')]

In [23]:
conn.rollback()

In [24]:
cur.execute("SELECT * FROM contact")

In [25]:
cur.fetchall()

[('kim', 30, 'kim@naver.com'),
 ('lee', 35, 'lee@daum.net'),
 ('park', 40, 'heo@coderby.com')]

In [26]:
conn.execute("UPDATE contact SET name='heo' WHERE email='heo@coderby.com'")

In [27]:
conn.commit()

In [28]:
cur.execute("SELECT * FROM contact")

In [29]:
cur.fetchall()

[('kim', 30, 'kim@naver.com'),
 ('lee', 35, 'lee@daum.net'),
 ('heo', 40, 'heo@coderby.com')]

In [30]:
conn.close()

### Oracle

In [31]:
import oracledb

In [32]:
oracle_dsn = oracledb.makedsn(host="localhost", port=1521, sid="xe")
oracle_dsn

'(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=xe)))'

In [33]:
conn = oracledb.connect(dsn=oracle_dsn, user="hr", password="hr")
conn

In [34]:
cursor = conn.cursor()

In [35]:
sql = "select first_name, last_name from employees"
cursor.execute(sql)

In [36]:
for name in cursor:
    print(name)

('Ellen', 'Abel')
('Sundar', 'Ande')
('Mozhe', 'Atkinson')
('Shelli', 'Baida')
('Amit', 'Banda')
('Elizabeth', 'Bates')
('Sarah', 'Bell')
('David', 'Bernstein')
('Laura', 'Bissot')
('Harrison', 'Bloom')
('Hermann', 'Brown')
('Alexis', 'Bull')
('Anthony', 'Cabrio')
('Gerald', 'Cambrault')
('Nanette', 'Cambrault')
('John', 'Chen')
('Kelly', 'Chung')
('Karen', 'Colmenares')
('Curtis', 'Davies')
('Pat', 'Davis')
('Julia', 'Dellinger')
('Jennifer', 'Dilly')
('Louise', 'Doran')
('Alberto', 'Errazuriz')
('Britney', 'Everett')
('Daniel', 'Faviet')
('Kevin', 'Feeney')
('Jean', 'Fleaur')
('Tayler', 'Fox')
('Adam', 'Fripp')
('Lex', 'Garcia')
('Ki', 'Gee')
('Girard', 'Geoni')
('William', 'Gietz')
('Douglas', 'Grant')
('Kimberely', 'Grant')
('Danielle', 'Greene')
('Nancy', 'Gruenberg')
('Peter', 'Hall')
('Shelley', 'Higgins')
('Guy', 'Himuro')
('Alyssa', 'Hutton')
('Valli', 'Jackson')
('Susan', 'Jacobs')
('Alexander', 'James')
('Charles', 'Johnson')
('Vance', 'Jones')
('Payam', 'Kaufling')
('Alexander', 'Khoo')
('Janette', 'King')
('Steven', 'King')
('Sundita', 'Kumar')
('Renske', 'Ladwig')
('James', 'Landry')
('David', 'Lee')
('Den', 'Li')
('Jack', 'Livingston')
('Jason', 'Mallin')
('Steven', 'Markle')
('James', 'Marlow')
('Michael', 'Martinez')
('Mattea', 'Marvins')
('Randall', 'Matos')
('Allan', 'McEwen')
('Samuel', 'McLeod')
('Irene', 'Mikkilineni')
('Bruce', 'Miller')
('Kevin', 'Mourgos')
('Julia', 'Nayer')
('Diana', 'Nguyen')
('Donald', 'OConnell')
('Christopher', 'Olsen')
('TJ', 'Olson')
('Lisa', 'Ozer')
('Karen', 'Partners')
('Joshua', 'Patel')
('Randall', 'Perkins')
('Hazel', 'Philtanker')
('Luis', 'Popp')
('Trenna', 'Rajs')
('Michael', 'Rogers')
('Nandita', 'Sarchand')
('Ismael', 'Sciarra')
('John', 'Seo')
('Sarath', 'Sewall')
('John', 'Singh')
('Lindsey', 'Smith')
('William', 'Smith')
('Stephen', 'Stiles')
('Martha', 'Sullivan')
('Patrick', 'Sully')
('Jonathon', 'Taylor')
('Winston', 'Taylor')
('Sigal', 'Tobias')
('Sean', 'Tucker')
('Oliver', 'Tuvault')
('Jose Manuel', 'Urman')
('Peter', 'Vargas')
('Timothy', 'Venzl')
('Clara', 'Vishney')
('Shanta', 'Vollman')
('Alana', 'Walsh')
('Matthew', 'Weiss')
('Jennifer', 'Whalen')
('David', 'Williams')
('Neena', 'Yang')
('Eleni', 'Zlotkey')

In [37]:
cursor.execute("select * from employees")

In [38]:
for emp in cursor:
    print(emp)

(100, 'Steven', 'King', 'SKING', '1.515.555.0100', datetime.datetime(2013, 6, 17, 0, 0), 'AD_PRES', 24000.0, None, None, 90)
(101, 'Neena', 'Yang', 'NYANG', '1.515.555.0101', datetime.datetime(2015, 9, 21, 0, 0), 'AD_VP', 17000.0, None, 100, 90)
(102, 'Lex', 'Garcia', 'LGARCIA', '1.515.555.0102', datetime.datetime(2011, 1, 13, 0, 0), 'AD_VP', 17000.0, None, 100, 90)
(103, 'Alexander', 'James', 'AJAMES', '1.590.555.0103', datetime.datetime(2016, 1, 3, 0, 0), 'IT_PROG', 9000.0, None, 102, 60)
(104, 'Bruce', 'Miller', 'BMILLER', '1.590.555.0104', datetime.datetime(2017, 5, 21, 0, 0), 'IT_PROG', 6000.0, None, 103, 60)
(105, 'David', 'Williams', 'DWILLIAMS', '1.590.555.0105', datetime.datetime(2015, 6, 25, 0, 0), 'IT_PROG', 4800.0, None, 103, 60)
(106, 'Valli', 'Jackson', 'VJACKSON', '1.590.555.0106', datetime.datetime(2016, 2, 5, 0, 0), 'IT_PROG', 4800.0, None, 103, 60)
(107, 'Diana', 'Nguyen', 'DNGUYEN', '1.590.555.0107', datetime.datetime(2017, 2, 7, 0, 0), 'IT_PROG', 4200.0, None, 103, 60)
(108, 'Nancy', 'Gruenberg', 'NGRUENBE', '1.515.555.0108', datetime.datetime(2012, 8, 17, 0, 0), 'FI_MGR', 12008.0, None, 101, 100)
(109, 'Daniel', 'Faviet', 'DFAVIET', '1.515.555.0109', datetime.datetime(2012, 8, 16, 0, 0), 'FI_ACCOUNT', 9000.0, None, 108, 100)
(110, 'John', 'Chen', 'JCHEN', '1.515.555.0110', datetime.datetime(2015, 9, 28, 0, 0), 'FI_ACCOUNT', 8200.0, None, 108, 100)
(111, 'Ismael', 'Sciarra', 'ISCIARRA', '1.515.555.0111', datetime.datetime(2015, 9, 30, 0, 0), 'FI_ACCOUNT', 7700.0, None, 108, 100)
(112, 'Jose Manuel', 'Urman', 'JMURMAN', '1.515.555.0112', datetime.datetime(2016, 3, 7, 0, 0), 'FI_ACCOUNT', 7800.0, None, 108, 100)
(113, 'Luis', 'Popp', 'LPOPP', '1.515.555.0113', datetime.datetime(2017, 12, 7, 0, 0), 'FI_ACCOUNT', 6900.0, None, 108, 100)
(114, 'Den', 'Li', 'DLI', '1.515.555.0114', datetime.datetime(2012, 12, 7, 0, 0), 'PU_MAN', 11000.0, None, 100, 30)
(115, 'Alexander', 'Khoo', 'AKHOO', '1.515.555.0115', datetime.datetime(2013, 5, 18, 0, 0), 'PU_CLERK', 3100.0, None, 114, 30)
(116, 'Shelli', 'Baida', 'SBAIDA', '1.515.555.0116', datetime.datetime(2015, 12, 24, 0, 0), 'PU_CLERK', 2900.0, None, 114, 30)
(117, 'Sigal', 'Tobias', 'STOBIAS', '1.515.555.0117', datetime.datetime(2015, 7, 24, 0, 0), 'PU_CLERK', 2800.0, None, 114, 30)
(118, 'Guy', 'Himuro', 'GHIMURO', '1.515.555.0118', datetime.datetime(2016, 11, 15, 0, 0), 'PU_CLERK', 2600.0, None, 114, 30)
(119, 'Karen', 'Colmenares', 'KCOLMENA', '1.515.555.0119', datetime.datetime(2017, 8, 10, 0, 0), 'PU_CLERK', 2500.0, None, 114, 30)
(120, 'Matthew', 'Weiss', 'MWEISS', '1.650.555.0120', datetime.datetime(2014, 7, 18, 0, 0), 'ST_MAN', 8000.0, None, 100, 50)
(121, 'Adam', 'Fripp', 'AFRIPP', '1.650.555.0121', datetime.datetime(2015, 4, 10, 0, 0), 'ST_MAN', 8200.0, None, 100, 50)
(122, 'Payam', 'Kaufling', 'PKAUFLIN', '1.650.555.0122', datetime.datetime(2013, 5, 1, 0, 0), 'ST_MAN', 7900.0, None, 100, 50)
(123, 'Shanta', 'Vollman', 'SVOLLMAN', '1.650.555.0123', datetime.datetime(2015, 10, 10, 0, 0), 'ST_MAN', 6500.0, None, 100, 50)
(124, 'Kevin', 'Mourgos', 'KMOURGOS', '1.650.555.0124', datetime.datetime(2017, 11, 16, 0, 0), 'ST_MAN', 5800.0, None, 100, 50)
(125, 'Julia', 'Nayer', 'JNAYER', '1.650.555.0125', datetime.datetime(2015, 7, 16, 0, 0), 'ST_CLERK', 3200.0, None, 120, 50)
(126, 'Irene', 'Mikkilineni', 'IMIKKILI', '1.650.555.0126', datetime.datetime(2016, 9, 28, 0, 0), 'ST_CLERK', 2700.0, None, 120, 50)
(127, 'James', 'Landry', 'JLANDRY', '1.650.555.0127', datetime.datetime(2017, 1, 14, 0, 0), 'ST_CLERK', 2400.0, None, 120, 50)
(128, 'Steven', 'Markle', 'SMARKLE', '1.650.555.0128', datetime.datetime(2018, 3, 8, 0, 0), 'ST_CLERK', 2200.0, None, 120, 50)
(129, 'Laura', 'Bissot', 'LBISSOT', '1.650.555.0129', datetime.datetime(2015, 8, 20, 0, 0), 'ST_CLERK', 3300.0, None, 121, 50)
(130, 'Mozhe', 'Atkinson', 'MATKINSO', '1.650.555.0130', datetime.datetime(2015, 10, 30, 0, 0), 'ST_CLERK', 2800.0, None, 121, 50)
(131, 'James', 'Marlow', 'JAMRLOW', '1.650.555.0131', datetime.datetime(2015, 2, 16, 0, 0), 'ST_CLERK', 2500.0, None, 121, 50)
(132, 'TJ', 'Olson', 'TJOLSON', '1.650.555.0132', datetime.datetime(2017, 4, 10, 0, 0), 'ST_CLERK', 2100.0, None, 121, 50)
(133, 'Jason', 'Mallin', 'JMALLIN', '1.650.555.0133', datetime.datetime(2014, 6, 14, 0, 0), 'ST_CLERK', 3300.0, None, 122, 50)
(134, 'Michael', 'Rogers', 'MROGERS', '1.650.555.0134', datetime.datetime(2016, 8, 26, 0, 0), 'ST_CLERK', 2900.0, None, 122, 50)
(135, 'Ki', 'Gee', 'KGEE', '1.650.555.0135', datetime.datetime(2017, 12, 12, 0, 0), 'ST_CLERK', 2400.0, None, 122, 50)
(136, 'Hazel', 'Philtanker', 'HPHILTAN', '1.650.555.0136', datetime.datetime(2018, 2, 6, 0, 0), 'ST_CLERK', 2200.0, None, 122, 50)
(137, 'Renske', 'Ladwig', 'RLADWIG', '1.650.555.0137', datetime.datetime(2013, 7, 14, 0, 0), 'ST_CLERK', 3600.0, None, 123, 50)
(138, 'Stephen', 'Stiles', 'SSTILES', '1.650.555.0138', datetime.datetime(2015, 10, 26, 0, 0), 'ST_CLERK', 3200.0, None, 123, 50)
(139, 'John', 'Seo', 'JSEO', '1.650.555.0139', datetime.datetime(2016, 2, 12, 0, 0), 'ST_CLERK', 2700.0, None, 123, 50)
(140, 'Joshua', 'Patel', 'JPATEL', '1.650.555.0140', datetime.datetime(2016, 4, 6, 0, 0), 'ST_CLERK', 2500.0, None, 123, 50)
(141, 'Trenna', 'Rajs', 'TRAJS', '1.650.555.0141', datetime.datetime(2013, 10, 17, 0, 0), 'ST_CLERK', 3500.0, None, 124, 50)
(142, 'Curtis', 'Davies', 'CDAVIES', '1.650.555.0142', datetime.datetime(2015, 1, 29, 0, 0), 'ST_CLERK', 3100.0, None, 124, 50)
(143, 'Randall', 'Matos', 'RMATOS', '1.650.555.0143', datetime.datetime(2016, 3, 15, 0, 0), 'ST_CLERK', 2600.0, None, 124, 50)
(144, 'Peter', 'Vargas', 'PVARGAS', '1.650.555.0144', datetime.datetime(2016, 7, 9, 0, 0), 'ST_CLERK', 2500.0, None, 124, 50)
(145, 'John', 'Singh', 'JSINGH', '44.1632.960000', datetime.datetime(2014, 10, 1, 0, 0), 'SA_MAN', 14000.0, 0.4, 100, 80)
(146, 'Karen', 'Partners', 'KPARTNER', '44.1632.960001', datetime.datetime(2015, 1, 5, 0, 0), 'SA_MAN', 13500.0, 0.3, 100, 80)
(147, 'Alberto', 'Errazuriz', 'AERRAZUR', '44.1632.960002', datetime.datetime(2015, 3, 10, 0, 0), 'SA_MAN', 12000.0, 0.3, 100, 80)
(148, 'Gerald', 'Cambrault', 'GCAMBRAU', '44.1632.960003', datetime.datetime(2017, 10, 15, 0, 0), 'SA_MAN', 11000.0, 0.3, 100, 80)
(149, 'Eleni', 'Zlotkey', 'EZLOTKEY', '44.1632.960004', datetime.datetime(2018, 1, 29, 0, 0), 'SA_MAN', 10500.0, 0.2, 100, 80)
(150, 'Sean', 'Tucker', 'STUCKER', '44.1632.960005', datetime.datetime(2015, 1, 30, 0, 0), 'SA_REP', 10000.0, 0.3, 145, 80)
(151, 'David', 'Bernstein', 'DBERNSTE', '44.1632.960006', datetime.datetime(2015, 3, 24, 0, 0), 'SA_REP', 9500.0, 0.25, 145, 80)
(152, 'Peter', 'Hall', 'PHALL', '44.1632.960007', datetime.datetime(2015, 8, 20, 0, 0), 'SA_REP', 9000.0, 0.25, 145, 80)
(153, 'Christopher', 'Olsen', 'COLSEN', '44.1632.960008', datetime.datetime(2016, 3, 30, 0, 0), 'SA_REP', 8000.0, 0.2, 145, 80)
(154, 'Nanette', 'Cambrault', 'NCAMBRAU', '44.1632.960009', datetime.datetime(2016, 12, 9, 0, 0), 'SA_REP', 7500.0, 0.2, 145, 80)
(155, 'Oliver', 'Tuvault', 'OTUVAULT', '44.1632.960010', datetime.datetime(2017, 11, 23, 0, 0), 'SA_REP', 7000.0, 0.15, 145, 80)
(156, 'Janette', 'King', 'JKING', '44.1632.960011', datetime.datetime(2014, 1, 30, 0, 0), 'SA_REP', 10000.0, 0.35, 146, 80)
(157, 'Patrick', 'Sully', 'PSULLY', '44.1632.960012', datetime.datetime(2014, 3, 4, 0, 0), 'SA_REP', 9500.0, 0.35, 146, 80)
(158, 'Allan', 'McEwen', 'AMCEWEN', '44.1632.960013', datetime.datetime(2014, 8, 1, 0, 0), 'SA_REP', 9000.0, 0.35, 146, 80)
(159, 'Lindsey', 'Smith', 'LSMITH', '44.1632.960014', datetime.datetime(2015, 3, 10, 0, 0), 'SA_REP', 8000.0, 0.3, 146, 80)
(160, 'Louise', 'Doran', 'LDORAN', '44.1632.960015', datetime.datetime(2015, 12, 15, 0, 0), 'SA_REP', 7500.0, 0.3, 146, 80)
(161, 'Sarath', 'Sewall', 'SSEWALL', '44.1632.960016', datetime.datetime(2016, 11, 3, 0, 0), 'SA_REP', 7000.0, 0.25, 146, 80)
(162, 'Clara', 'Vishney', 'CVISHNEY', '44.1632.960017', datetime.datetime(2015, 11, 11, 0, 0), 'SA_REP', 10500.0, 0.25, 147, 80)
(163, 'Danielle', 'Greene', 'DGREENE', '44.1632.960018', datetime.datetime(2017, 3, 19, 0, 0), 'SA_REP', 9500.0, 0.15, 147, 80)
(164, 'Mattea', 'Marvins', 'MMARVINS', '44.1632.960019', datetime.datetime(2018, 1, 24, 0, 0), 'SA_REP', 7200.0, 0.1, 147, 80)
(165, 'David', 'Lee', 'DLEE', '44.1632.960020', datetime.datetime(2018, 2, 23, 0, 0), 'SA_REP', 6800.0, 0.1, 147, 80)
(166, 'Sundar', 'Ande', 'SANDE', '44.1632.960021', datetime.datetime(2018, 3, 24, 0, 0), 'SA_REP', 6400.0, 0.1, 147, 80)
(167, 'Amit', 'Banda', 'ABANDA', '44.1632.960022', datetime.datetime(2018, 4, 21, 0, 0), 'SA_REP', 6200.0, 0.1, 147, 80)
(168, 'Lisa', 'Ozer', 'LOZER', '44.1632.960023', datetime.datetime(2015, 3, 11, 0, 0), 'SA_REP', 11500.0, 0.25, 148, 80)
(169, 'Harrison', 'Bloom', 'HBLOOM', '44.1632.960024', datetime.datetime(2016, 3, 23, 0, 0), 'SA_REP', 10000.0, 0.2, 148, 80)
(170, 'Tayler', 'Fox', 'TFOX', '44.1632.960025', datetime.datetime(2016, 1, 24, 0, 0), 'SA_REP', 9600.0, 0.2, 148, 80)
(171, 'William', 'Smith', 'WSMITH', '44.1632.960026', datetime.datetime(2017, 2, 23, 0, 0), 'SA_REP', 7400.0, 0.15, 148, 80)
(172, 'Elizabeth', 'Bates', 'EBATES', '44.1632.960027', datetime.datetime(2017, 3, 24, 0, 0), 'SA_REP', 7300.0, 0.15, 148, 80)
(173, 'Sundita', 'Kumar', 'SKUMAR', '44.1632.960028', datetime.datetime(2018, 4, 21, 0, 0), 'SA_REP', 6100.0, 0.1, 148, 80)
(174, 'Ellen', 'Abel', 'EABEL', '44.1632.960029', datetime.datetime(2014, 5, 11, 0, 0), 'SA_REP', 11000.0, 0.3, 149, 80)
(175, 'Alyssa', 'Hutton', 'AHUTTON', '44.1632.960030', datetime.datetime(2015, 3, 19, 0, 0), 'SA_REP', 8800.0, 0.25, 149, 80)
(176, 'Jonathon', 'Taylor', 'JTAYLOR', '44.1632.960031', datetime.datetime(2016, 3, 24, 0, 0), 'SA_REP', 8600.0, 0.2, 149, 80)
(177, 'Jack', 'Livingston', 'JLIVINGS', '44.1632.960032', datetime.datetime(2016, 4, 23, 0, 0), 'SA_REP', 8400.0, 0.2, 149, 80)
(178, 'Kimberely', 'Grant', 'KGRANT', '44.1632.960033', datetime.datetime(2017, 5, 24, 0, 0), 'SA_REP', 7000.0, 0.15, 149, None)
(179, 'Charles', 'Johnson', 'CJOHNSON', '44.1632.960034', datetime.datetime(2018, 1, 4, 0, 0), 'SA_REP', 6200.0, 0.1, 149, 80)
(180, 'Winston', 'Taylor', 'WTAYLOR', '1.650.555.0145', datetime.datetime(2016, 1, 24, 0, 0), 'SH_CLERK', 3200.0, None, 120, 50)
(181, 'Jean', 'Fleaur', 'JFLEAUR', '1.650.555.0146', datetime.datetime(2016, 2, 23, 0, 0), 'SH_CLERK', 3100.0, None, 120, 50)
(182, 'Martha', 'Sullivan', 'MSULLIVA', '1.650.555.0147', datetime.datetime(2017, 6, 21, 0, 0), 'SH_CLERK', 2500.0, None, 120, 50)
(183, 'Girard', 'Geoni', 'GGEONI', '1.650.555.0148', datetime.datetime(2018, 2, 3, 0, 0), 'SH_CLERK', 2800.0, None, 120, 50)
(184, 'Nandita', 'Sarchand', 'NSARCHAN', '1.650.555.0149', datetime.datetime(2014, 1, 27, 0, 0), 'SH_CLERK', 4200.0, None, 121, 50)
(185, 'Alexis', 'Bull', 'ABULL', '1.650.555.0150', datetime.datetime(2015, 2, 20, 0, 0), 'SH_CLERK', 4100.0, None, 121, 50)
(186, 'Julia', 'Dellinger', 'JDELLING', '1.650.555.0151', datetime.datetime(2016, 6, 24, 0, 0), 'SH_CLERK', 3400.0, None, 121, 50)
(187, 'Anthony', 'Cabrio', 'ACABRIO', '1.650.555.0152', datetime.datetime(2017, 2, 7, 0, 0), 'SH_CLERK', 3000.0, None, 121, 50)
(188, 'Kelly', 'Chung', 'KCHUNG', '1.650.555.0153', datetime.datetime(2015, 6, 14, 0, 0), 'SH_CLERK', 3800.0, None, 122, 50)
(189, 'Jennifer', 'Dilly', 'JDILLY', '1.650.555.0154', datetime.datetime(2015, 8, 13, 0, 0), 'SH_CLERK', 3600.0, None, 122, 50)
(190, 'Timothy', 'Venzl', 'TVENZL', '1.650.555.0155', datetime.datetime(2016, 7, 11, 0, 0), 'SH_CLERK', 2900.0, None, 122, 50)
(191, 'Randall', 'Perkins', 'RPERKINS', '1.650.555.0156', datetime.datetime(2017, 12, 19, 0, 0), 'SH_CLERK', 2500.0, None, 122, 50)
(192, 'Sarah', 'Bell', 'SBELL', '1.650.555.0157', datetime.datetime(2014, 2, 4, 0, 0), 'SH_CLERK', 4000.0, None, 123, 50)
(193, 'Britney', 'Everett', 'BEVERETT', '1.650.555.0158', datetime.datetime(2015, 3, 3, 0, 0), 'SH_CLERK', 3900.0, None, 123, 50)
(194, 'Samuel', 'McLeod', 'SMCLEOD', '1.650.555.0159', datetime.datetime(2016, 7, 1, 0, 0), 'SH_CLERK', 3200.0, None, 123, 50)
(195, 'Vance', 'Jones', 'VJONES', '1.650.555.0160', datetime.datetime(2017, 3, 17, 0, 0), 'SH_CLERK', 2800.0, None, 123, 50)
(196, 'Alana', 'Walsh', 'AWALSH', '1.650.555.0161', datetime.datetime(2016, 4, 24, 0, 0), 'SH_CLERK', 3100.0, None, 124, 50)
(197, 'Kevin', 'Feeney', 'KFEENEY', '1.650.555.0162', datetime.datetime(2016, 5, 23, 0, 0), 'SH_CLERK', 3000.0, None, 124, 50)
(198, 'Donald', 'OConnell', 'DOCONNEL', '1.650.555.0163', datetime.datetime(2017, 6, 21, 0, 0), 'SH_CLERK', 2600.0, None, 124, 50)
(199, 'Douglas', 'Grant', 'DGRANT', '1.650.555.0164', datetime.datetime(2018, 1, 13, 0, 0), 'SH_CLERK', 2600.0, None, 124, 50)
(200, 'Jennifer', 'Whalen', 'JWHALEN', '1.515.555.0165', datetime.datetime(2013, 9, 17, 0, 0), 'AD_ASST', 4400.0, None, 101, 10)
(201, 'Michael', 'Martinez', 'MMARTINE', '1.515.555.0166', datetime.datetime(2014, 2, 17, 0, 0), 'MK_MAN', 13000.0, None, 100, 20)
(202, 'Pat', 'Davis', 'PDAVIS', '1.603.555.0167', datetime.datetime(2015, 8, 17, 0, 0), 'MK_REP', 6000.0, None, 201, 20)
(203, 'Susan', 'Jacobs', 'SJACOBS', '1.515.555.0168', datetime.datetime(2012, 6, 7, 0, 0), 'HR_REP', 6500.0, None, 101, 40)
(204, 'Hermann', 'Brown', 'HBROWN', '1.515.555.0169', datetime.datetime(2012, 6, 7, 0, 0), 'PR_REP', 10000.0, None, 101, 70)
(205, 'Shelley', 'Higgins', 'SHIGGINS', '1.515.555.0170', datetime.datetime(2012, 6, 7, 0, 0), 'AC_MGR', 12008.0, None, 101, 110)
(206, 'William', 'Gietz', 'WGIETZ', '1.515.555.0171', datetime.datetime(2012, 6, 7, 0, 0), 'AC_ACCOUNT', 8300.0, None, 205, 110)

In [39]:
cursor.execute("select * from employees where department_id = :dept_id",
               {"dept_id":50})

In [40]:
for emp in cursor:
    print(emp)

(120, 'Matthew', 'Weiss', 'MWEISS', '1.650.555.0120', datetime.datetime(2014, 7, 18, 0, 0), 'ST_MAN', 8000.0, None, 100, 50)
(121, 'Adam', 'Fripp', 'AFRIPP', '1.650.555.0121', datetime.datetime(2015, 4, 10, 0, 0), 'ST_MAN', 8200.0, None, 100, 50)
(122, 'Payam', 'Kaufling', 'PKAUFLIN', '1.650.555.0122', datetime.datetime(2013, 5, 1, 0, 0), 'ST_MAN', 7900.0, None, 100, 50)
(123, 'Shanta', 'Vollman', 'SVOLLMAN', '1.650.555.0123', datetime.datetime(2015, 10, 10, 0, 0), 'ST_MAN', 6500.0, None, 100, 50)
(124, 'Kevin', 'Mourgos', 'KMOURGOS', '1.650.555.0124', datetime.datetime(2017, 11, 16, 0, 0), 'ST_MAN', 5800.0, None, 100, 50)
(125, 'Julia', 'Nayer', 'JNAYER', '1.650.555.0125', datetime.datetime(2015, 7, 16, 0, 0), 'ST_CLERK', 3200.0, None, 120, 50)
(126, 'Irene', 'Mikkilineni', 'IMIKKILI', '1.650.555.0126', datetime.datetime(2016, 9, 28, 0, 0), 'ST_CLERK', 2700.0, None, 120, 50)
(127, 'James', 'Landry', 'JLANDRY', '1.650.555.0127', datetime.datetime(2017, 1, 14, 0, 0), 'ST_CLERK', 2400.0, None, 120, 50)
(128, 'Steven', 'Markle', 'SMARKLE', '1.650.555.0128', datetime.datetime(2018, 3, 8, 0, 0), 'ST_CLERK', 2200.0, None, 120, 50)
(129, 'Laura', 'Bissot', 'LBISSOT', '1.650.555.0129', datetime.datetime(2015, 8, 20, 0, 0), 'ST_CLERK', 3300.0, None, 121, 50)
(130, 'Mozhe', 'Atkinson', 'MATKINSO', '1.650.555.0130', datetime.datetime(2015, 10, 30, 0, 0), 'ST_CLERK', 2800.0, None, 121, 50)
(131, 'James', 'Marlow', 'JAMRLOW', '1.650.555.0131', datetime.datetime(2015, 2, 16, 0, 0), 'ST_CLERK', 2500.0, None, 121, 50)
(132, 'TJ', 'Olson', 'TJOLSON', '1.650.555.0132', datetime.datetime(2017, 4, 10, 0, 0), 'ST_CLERK', 2100.0, None, 121, 50)
(133, 'Jason', 'Mallin', 'JMALLIN', '1.650.555.0133', datetime.datetime(2014, 6, 14, 0, 0), 'ST_CLERK', 3300.0, None, 122, 50)
(134, 'Michael', 'Rogers', 'MROGERS', '1.650.555.0134', datetime.datetime(2016, 8, 26, 0, 0), 'ST_CLERK', 2900.0, None, 122, 50)
(135, 'Ki', 'Gee', 'KGEE', '1.650.555.0135', datetime.datetime(2017, 12, 12, 0, 0), 'ST_CLERK', 2400.0, None, 122, 50)
(136, 'Hazel', 'Philtanker', 'HPHILTAN', '1.650.555.0136', datetime.datetime(2018, 2, 6, 0, 0), 'ST_CLERK', 2200.0, None, 122, 50)
(137, 'Renske', 'Ladwig', 'RLADWIG', '1.650.555.0137', datetime.datetime(2013, 7, 14, 0, 0), 'ST_CLERK', 3600.0, None, 123, 50)
(138, 'Stephen', 'Stiles', 'SSTILES', '1.650.555.0138', datetime.datetime(2015, 10, 26, 0, 0), 'ST_CLERK', 3200.0, None, 123, 50)
(139, 'John', 'Seo', 'JSEO', '1.650.555.0139', datetime.datetime(2016, 2, 12, 0, 0), 'ST_CLERK', 2700.0, None, 123, 50)
(140, 'Joshua', 'Patel', 'JPATEL', '1.650.555.0140', datetime.datetime(2016, 4, 6, 0, 0), 'ST_CLERK', 2500.0, None, 123, 50)
(141, 'Trenna', 'Rajs', 'TRAJS', '1.650.555.0141', datetime.datetime(2013, 10, 17, 0, 0), 'ST_CLERK', 3500.0, None, 124, 50)
(142, 'Curtis', 'Davies', 'CDAVIES', '1.650.555.0142', datetime.datetime(2015, 1, 29, 0, 0), 'ST_CLERK', 3100.0, None, 124, 50)
(143, 'Randall', 'Matos', 'RMATOS', '1.650.555.0143', datetime.datetime(2016, 3, 15, 0, 0), 'ST_CLERK', 2600.0, None, 124, 50)
(144, 'Peter', 'Vargas', 'PVARGAS', '1.650.555.0144', datetime.datetime(2016, 7, 9, 0, 0), 'ST_CLERK', 2500.0, None, 124, 50)
(180, 'Winston', 'Taylor', 'WTAYLOR', '1.650.555.0145', datetime.datetime(2016, 1, 24, 0, 0), 'SH_CLERK', 3200.0, None, 120, 50)
(181, 'Jean', 'Fleaur', 'JFLEAUR', '1.650.555.0146', datetime.datetime(2016, 2, 23, 0, 0), 'SH_CLERK', 3100.0, None, 120, 50)
(182, 'Martha', 'Sullivan', 'MSULLIVA', '1.650.555.0147', datetime.datetime(2017, 6, 21, 0, 0), 'SH_CLERK', 2500.0, None, 120, 50)
(183, 'Girard', 'Geoni', 'GGEONI', '1.650.555.0148', datetime.datetime(2018, 2, 3, 0, 0), 'SH_CLERK', 2800.0, None, 120, 50)
(184, 'Nandita', 'Sarchand', 'NSARCHAN', '1.650.555.0149', datetime.datetime(2014, 1, 27, 0, 0), 'SH_CLERK', 4200.0, None, 121, 50)
(185, 'Alexis', 'Bull', 'ABULL', '1.650.555.0150', datetime.datetime(2015, 2, 20, 0, 0), 'SH_CLERK', 4100.0, None, 121, 50)
(186, 'Julia', 'Dellinger', 'JDELLING', '1.650.555.0151', datetime.datetime(2016, 6, 24, 0, 0), 'SH_CLERK', 3400.0, None, 121, 50)
(187, 'Anthony', 'Cabrio', 'ACABRIO', '1.650.555.0152', datetime.datetime(2017, 2, 7, 0, 0), 'SH_CLERK', 3000.0, None, 121, 50)
(188, 'Kelly', 'Chung', 'KCHUNG', '1.650.555.0153', datetime.datetime(2015, 6, 14, 0, 0), 'SH_CLERK', 3800.0, None, 122, 50)
(189, 'Jennifer', 'Dilly', 'JDILLY', '1.650.555.0154', datetime.datetime(2015, 8, 13, 0, 0), 'SH_CLERK', 3600.0, None, 122, 50)
(190, 'Timothy', 'Venzl', 'TVENZL', '1.650.555.0155', datetime.datetime(2016, 7, 11, 0, 0), 'SH_CLERK', 2900.0, None, 122, 50)
(191, 'Randall', 'Perkins', 'RPERKINS', '1.650.555.0156', datetime.datetime(2017, 12, 19, 0, 0), 'SH_CLERK', 2500.0, None, 122, 50)
(192, 'Sarah', 'Bell', 'SBELL', '1.650.555.0157', datetime.datetime(2014, 2, 4, 0, 0), 'SH_CLERK', 4000.0, None, 123, 50)
(193, 'Britney', 'Everett', 'BEVERETT', '1.650.555.0158', datetime.datetime(2015, 3, 3, 0, 0), 'SH_CLERK', 3900.0, None, 123, 50)
(194, 'Samuel', 'McLeod', 'SMCLEOD', '1.650.555.0159', datetime.datetime(2016, 7, 1, 0, 0), 'SH_CLERK', 3200.0, None, 123, 50)
(195, 'Vance', 'Jones', 'VJONES', '1.650.555.0160', datetime.datetime(2017, 3, 17, 0, 0), 'SH_CLERK', 2800.0, None, 123, 50)
(196, 'Alana', 'Walsh', 'AWALSH', '1.650.555.0161', datetime.datetime(2016, 4, 24, 0, 0), 'SH_CLERK', 3100.0, None, 124, 50)
(197, 'Kevin', 'Feeney', 'KFEENEY', '1.650.555.0162', datetime.datetime(2016, 5, 23, 0, 0), 'SH_CLERK', 3000.0, None, 124, 50)
(198, 'Donald', 'OConnell', 'DOCONNEL', '1.650.555.0163', datetime.datetime(2017, 6, 21, 0, 0), 'SH_CLERK', 2600.0, None, 124, 50)
(199, 'Douglas', 'Grant', 'DGRANT', '1.650.555.0164', datetime.datetime(2018, 1, 13, 0, 0), 'SH_CLERK', 2600.0, None, 124, 50)

In [41]:
params = {"dept_id":50, "mgr_id":124}
cursor.execute("""select * from employees 
    where department_id=:dept_id and manager_id=:mgr_id""",
               **params)

In [42]:
for emp in cursor:
    print(emp)

(141, 'Trenna', 'Rajs', 'TRAJS', '1.650.555.0141', datetime.datetime(2013, 10, 17, 0, 0), 'ST_CLERK', 3500.0, None, 124, 50)
(142, 'Curtis', 'Davies', 'CDAVIES', '1.650.555.0142', datetime.datetime(2015, 1, 29, 0, 0), 'ST_CLERK', 3100.0, None, 124, 50)
(143, 'Randall', 'Matos', 'RMATOS', '1.650.555.0143', datetime.datetime(2016, 3, 15, 0, 0), 'ST_CLERK', 2600.0, None, 124, 50)
(144, 'Peter', 'Vargas', 'PVARGAS', '1.650.555.0144', datetime.datetime(2016, 7, 9, 0, 0), 'ST_CLERK', 2500.0, None, 124, 50)
(196, 'Alana', 'Walsh', 'AWALSH', '1.650.555.0161', datetime.datetime(2016, 4, 24, 0, 0), 'SH_CLERK', 3100.0, None, 124, 50)
(197, 'Kevin', 'Feeney', 'KFEENEY', '1.650.555.0162', datetime.datetime(2016, 5, 23, 0, 0), 'SH_CLERK', 3000.0, None, 124, 50)
(198, 'Donald', 'OConnell', 'DOCONNEL', '1.650.555.0163', datetime.datetime(2017, 6, 21, 0, 0), 'SH_CLERK', 2600.0, None, 124, 50)
(199, 'Douglas', 'Grant', 'DGRANT', '1.650.555.0164', datetime.datetime(2018, 1, 13, 0, 0), 'SH_CLERK', 2600.0, None, 124, 50)

In [43]:
cursor.execute("select * from employees")

In [44]:
from pandas import DataFrame

emp_df = DataFrame(cursor.fetchall())
cursor.rowcount

107

In [45]:
emp_df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,100,Steven,King,SKING,1.515.555.0100,2013-06-17,AD_PRES,24000.0,NaN,NaN,90.0
1,101,Neena,Yang,NYANG,1.515.555.0101,2015-09-21,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,Garcia,LGARCIA,1.515.555.0102,2011-01-13,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,James,AJAMES,1.590.555.0103,2016-01-03,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Miller,BMILLER,1.590.555.0104,2017-05-21,IT_PROG,6000.0,NaN,103.0,60.0

In [46]:
cursor.description

[('EMPLOYEE_ID', <DbType DB_TYPE_NUMBER>, 7, None, 6, 0, False),
 ('FIRST_NAME', <DbType DB_TYPE_VARCHAR>, 20, 20, None, None, True),
 ('LAST_NAME', <DbType DB_TYPE_VARCHAR>, 25, 25, None, None, False),
 ('EMAIL', <DbType DB_TYPE_VARCHAR>, 25, 25, None, None, False),
 ('PHONE_NUMBER', <DbType DB_TYPE_VARCHAR>, 20, 20, None, None, True),
 ('HIRE_DATE', <DbType DB_TYPE_DATE>, 23, None, None, None, False),
 ('JOB_ID', <DbType DB_TYPE_VARCHAR>, 10, 10, None, None, False),
 ('SALARY', <DbType DB_TYPE_NUMBER>, 12, None, 8, 2, True),
 ('COMMISSION_PCT', <DbType DB_TYPE_NUMBER>, 6, None, 2, 2, True),
 ('MANAGER_ID', <DbType DB_TYPE_NUMBER>, 7, None, 6, 0, True),
 ('DEPARTMENT_ID', <DbType DB_TYPE_NUMBER>, 5, None, 4, 0, True)]

In [47]:
col_names = [ row[0] for row in cursor.description ]
col_names

['EMPLOYEE_ID',
 'FIRST_NAME',
 'LAST_NAME',
 'EMAIL',
 'PHONE_NUMBER',
 'HIRE_DATE',
 'JOB_ID',
 'SALARY',
 'COMMISSION_PCT',
 'MANAGER_ID',
 'DEPARTMENT_ID']

In [48]:
emp_df.columns = col_names
emp_df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,1.515.555.0100,2013-06-17,AD_PRES,24000.0,NaN,NaN,90.0
1,101,Neena,Yang,NYANG,1.515.555.0101,2015-09-21,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,Garcia,LGARCIA,1.515.555.0102,2011-01-13,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,James,AJAMES,1.590.555.0103,2016-01-03,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Miller,BMILLER,1.590.555.0104,2017-05-21,IT_PROG,6000.0,NaN,103.0,60.0

### 연습문제

In [49]:
# import oracledb as oracle
# oracle_dsn = oracle.makedsn(host="localhost", port=1521, sid="xe")
# conn = oracle.connect(dsn=oracle_dsn, user="hr", password="hr")

In [50]:
import sqlite3

In [51]:
class Member:
    def __init__(self, name, phone, email, age, grade, etc):
        self.name = name
        self.phone = phone
        self.email = email
        self.age = age
        self.grade = grade
        self.etc = etc
        
    def __str__(self):
        return ("name: {}, phone: {}, email: {}, age: {}, grade: {}"\
                .fomat(self.name, self.phone, self.email, self.age, 
                       self.grade, self.etc))
    
    def to_dict(self):
        return {"name":self.name, "phone":self.phone, "email":self.email,
                "age":self.age, "grade":self.grade, "etc":self.etc}

In [52]:
def insert_member_info():
    cursor = conn.cursor()
    name = input("이름: ")
    phone = input("전화번호: ")
    email = input("이메일: ")
    age = input("나이: ")
    grade = input("고객등급(1~5): ")
    etc = input("기타정보: ")
    member = Member(name, phone, email, age, grade, etc)
    cursor.execute("""insert into member_db values 
                      (:name, :phone, :email, :age, :grade, :etc)""",
                   member.to_dict())

In [53]:
import pandas as pd
def get_all_members():
    cursor=conn.cursor()
    cursor.execute("select * from member_db")
    for member in cursor:
        print(member)

In [54]:
def delete_member(email):
    cursor = conn.cursor();
    cursor.execute("delete from member_db where email=:email",
                   {"email":email})

In [55]:
def search_member(name):
    cursor = conn.cursor()
    cursor.execute("select * from member_db where name=:name",
                   {"name":name})
    for member in cursor:
        print(member)

In [56]:
def export_member():
    file_name = input("파일명을 입력하세요.")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM member_db")
    members = cursor.fetchall()
    colnames = [ row[0] for row in cursor.description ]
    import csv
    with open(file_name, 'w', newline='', encoding="UTF8") as file:
        w = csv.writer(file, quoting=csv.QUOTE_NONNUMERIC)
        w.writerow(colnames)
        w.writerows(members)

In [57]:
def print_menu():
    print("1.입력", "2.전체조회", "3.이름으로 조회", "4.삭제", "5.내보내기(CSV)", 
          "0. 종료", sep=" | ", end="")
    menu = input("메뉴선택: ")
    return int(menu)

In [58]:
def main():
    while True:
        menu = print_menu()
        if menu==1:
            insert_member_info()
            conn.commit()
        elif menu==2:
            get_all_members()
        elif menu==3:
            name = input("찾고 싶은 회원의 이름을 입력하세요.")
            search_member(name)
        elif menu==4:
            email = input("삭제할 회원의 이메일을 입력하세요.")
            delete_member(email)
            conn.commit()
        elif menu==5:
            export_member()
        elif menu==0:
            conn.close()
            break

In [60]:
if __name__ == '__main__':
    global conn
    conn = sqlite3.connect("member.db")
    main()

1.입력 | 2.전체조회 | 3.이름으로 조회 | 4.삭제 | 5.내보내기(CSV) | 0. 종료

In [ ]:
if __name__ == '__main__':
    global conn
    conn = sqlite3.connect("member.db")
    main()

In [ ]:
import oracledb as oracle
oracle_dsn = oracle.makedsn(host="localhost", port=1521, sid="xe")
if __name__ == '__main__':
    global conn
    conn = oracle.connect(dsn=oracle_dsn, user="hr", password="hr")
    main()

In [ ]:
import oracledb
oracle_dsn = oracledb.makedsn(host="localhost", port=1521, sid="xe")
conn = oracledb.connect(dsn=oracle_dsn, user="hr", password="hr")